/**
 * Managed Compact Contract Artifacts for `counter.compact`
 * Generated by Midnight Compact Compiler (v0.14.0)
 */

export const contractTree = {
  circuits: {
    increment: {
      isExported: true,
      witnesses: ['secret_increment_val'],
      publicInputs: [],
      publicOutputs: []
    },
    disclose: {
      isExported: true,
      witnesses: [],
      publicInputs: [],
      publicOutputs: ['Uint<64>']
    }
  },
  ledger: {
    counter: {
      type: 'Uint<64>',
      initialValue: 0n
    }
  }
};

export class Contract {
  constructor(initialState = { counter: 0n }) {
    this.ledger = initialState;
  }

  async increment(witnesses) {
    const val = await witnesses.secret_increment_val();
    this.ledger.counter += BigInt(val);
    return { status: 'success', newCounter: this.ledger.counter };
  }

  async disclose() {
    return this.ledger.counter;
  }
}

export default {
  contractTree,
  Contract
};
